### PR TITLE
Add AppVeyor CI support

### PR DESCRIPTION
**Pull request by adrianbroher**
Playground.

### CODE REVIEW

**Comment by adrianbroher** [comment]
@rougier  At lease on the AppVeyor side of things this should be set up properly.  Can you please check if there was a webhook installed for the AppVeyorCI (Project Settings > Webhooks should list _https://ci.appveyor.com/api/github/webhook  (pull_request and push)_)?

**Comment by rougier** [comment]
No, I don't see it, only Zenodo. I can try to add it by hand but I would need more information

**Comment by rougier** [comment]
I just added the AppVeyor hook.

**Comment by rougier** [comment]
Can you access AppVeyour output by the way ?

After merge:
```
CMake Error at CMakeLists.txt:96 (message):
  `M_PI` not defined in `math.h`.
-- Configuring incomplete, errors occurred!
```

**Comment by adrianbroher** [comment]
Undoing the merge.  This is intentional playground.

**Comment by adrianbroher** [comment]
> Can you access AppVeyour output by the way ?

Yes:  https://ci.appveyor.com/project/adrianbroher/freetype-gl

**Comment by rougier** [comment]
Sorry for the merge. I guess I'll configure appveyor to track the appveyor branch.

**Comment by rougier** [comment]
Done.

**Comment by adrianbroher** [comment]
I'm confused:

You added another project under your name?

**Comment by rougier** [comment]
Yes. From your question I guess this is not the way to go...
AppVeyor hook was absent from the freetype-gl settings

**Comment by adrianbroher** [comment]
Well, okay.  I will ask for guidance again after the the appveyor docs.

**Comment by rougier** [comment]
I've never used AppVeyor before, I might be wrong. I'll check documentation as well.

**Comment by adrianbroher** [comment]
What I found out so far:

Creating a webhook on github requires Administrator permissions.  When somebody creates a project Appveyor installs only a webhook when that person has said admin rights on github for the repository.

You can recreate a webhook manually if the automatic creation for some reason: http://help.appveyor.com/discussions/questions/2272-github-webhook-deleted-how-to-recreate

This seems to work so far. I force pushed something onto the `appveyor` branch and that triggered a build (currently failing of course).

Regarding the permissions: it's complex.  An account on AppVeyor is more like an Github Organization than a regular account.  You can add collaborators to the AppVeyor accounts in a specific role.  For now there is nothing interesting here for this project IMO.  https://www.appveyor.com/docs/team-setup

**Pull request merged**
