### PR TITLE
Freetype-gl with travis-ci 

### PR DESCRIPTION
**Pull request by pelallemant**
These modifications allow you to do continous-integration with Travis-CI

You have to configure the project for travis (in the settings of your github project). You can use your github account on travis (it is synchronised with your github account if you allow it).

I warn you: when you push a project, it create a "build request", and it will only begin when their server is able to do it: there are a lot of free projects on travis, so it can take 10 mins before the build start.

Normally you don't have to change what I wrote in the configuration files, I already replaced 'crakouille/freetype-gl' per 'rougier/freetype-gl' (so my last build fail, but yours will succeed).

### CODE REVIEW

**Comment by rougier** [comment]
Veyr sorry for not merging your travis configuration in time.
Would you consider submit it again (after merging of pending requests) ?

**Comment by pelallemant** [comment]
I'm working on it.
I removed the Makefile too and added it in the .gitignore (the Makefile is generated with CMake).

**Comment by pelallemant** [comment]
https://travis-ci.org/pelallemant/freetype-gl/builds/60187474 passed :) 
Normally, you just need to activate travis-ci hook for this project, then merge the pull request.

**Comment by rougier** [comment]
Thanks ! I just activated the Travis hook.
But why everybody wants to suppress my beloved hand crafted Makefile :sob: 

Ok, R.I.P. Makefile.

**Comment by adrianbroher** [comment]
> But why everybody wants to suppress my beloved hand crafted Makefile

Because they're hand crafted. ;)

On a more serious note: As soon as you start with recursive Makefiles (for subdirectories), conditional features Makefile IMO get unmaintainable pretty  fast.

**Comment by rougier** [comment]
I know, but still...

**Comment by pelallemant** [comment]
https://travis-ci.org/rougier/freetype-gl build passed, and now https://github.com/rougier/freetype-gl with a green build-status bar ;) Thanks for the update.
I removed the makefile considering you were using cmake, sorry if it was not planned.

**Comment by rougier** [comment]
No problem, I should have removed it a long time ago. It's only sentimental :smile:

**Pull request merged**
