### PR TITLE
Move demo applications into a dedicated demos folder

### PR DESCRIPTION
**Pull request by adrianbroher**
This simplifies the CMake build files and separates out the optional
parts of the library in a more prominent way.

### CODE REVIEW

**Comment by rougier** [comment]
Thanks, this should have been done a long time ago...
I have to test and adapt the Makefile as well.

**Comment by adrianbroher** [comment]
> I have to test and *adapt the Makefile as well*.

I can take a look at that. But to be honest: I think that is unnecessary work, given the project provides a working CMake build system.

**Comment by rougier** [comment]
Yes, I know you're right but I'm so used to makefiles...

**Comment by rougier** [comment]
You can forget about the raw Makefile, it get removed with the Travis PR #18.
I'm waiting for travis feedback now then I'll test and merge.

**Comment by adrianbroher** [comment]
> I'm waiting for travis feedback now then I'll test and merge.

Please don't merge yet. I was a bit eager when moving around stuff, I will rebase a fix later that day.

**Comment by rougier** [comment]
Ok, just ping me.

**Comment by adrianbroher** [comment]
> Ok, just ping me.

Ping.

**Comment by rougier** [comment]
Pong.

**Pull request merged**
