### PR TITLE
Fonts

### PR DESCRIPTION
**Pull request by burito**
While I'm doing this I might as well do the job properly.

Obelix is unclearly licensed, it's out. Replaced with [Sigmar One](https://www.google.com/fonts/specimen/Sigmar+One). ``demo-cartoon.c`` updated accordingly.

Also added are [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro), [Source Code Pro](https://www.google.com/fonts/specimen/Source+Code+Pro), [Old Standard TT](https://www.google.com/fonts/specimen/Old+Standard+TT) and [Lobster](https://www.google.com/fonts/specimen/Lobster).

I don't think Makefiles are the place to list font dependancies, removed.

### CODE REVIEW

**Comment by rougier** [comment]
Not fan of sigmar one font... Let me try to look for another one.

**Comment by burito** [comment]
I can understand that, it was the first wide font that Google Fonts gave me. A little too wide, but it's a start.

**Comment by burito** [comment]
Thought I should prod you about font selection. My method, head over to [Google Fonts](http://www.google.com/fonts), click on "Thickness" and slide it towards the right.

[Luckiest Guy](http://www.google.com/fonts/specimen/Luckiest+Guy) seems to be in a similar vein to Obelix.
[Permanent Marker](http://www.google.com/fonts/specimen/Permanent+Marker), [Slackey](http://www.google.com/fonts/specimen/Slackey) and [Trade Winds](http://www.google.com/fonts/specimen/Trade+Winds) also seem like they could be a good fit.

**Comment by rougier** [comment]
Sorry, I totally forgot to look for fonts. Thansk for finding and selecting them.
I you're ok, I would choose the "Luckiest Guy" among your selection and then we can merge/close this PR (you may need to rebase).

**Pull request closed without merging**
