### PR TITLE
Add MSVS project files for building under Windows

### PR DESCRIPTION
**Pull request by namaenonaimumei**
Project files for base slib building with Visual Studio, compiled with vc141 (2017), vc142 works aswell.

* no changes for repository files, only `./VisualC/` has been added.
* build everything under `./VisualC/`, binaries output to `./VisualC/bin/`
* use dependencies provided under `./Windows/`

Runtime tested with freetype-2.10.4 windows static/shared binaries.

This doesn't account for files added in rougier/freetype-gl/pull/242

### CODE REVIEW

**Comment by rougier** [comment]
Thanks. I've not way to test it. Is that possible to add a build test on AppVeyor?

**Comment by namaenonaimumei** [comment]
I can try, but I can't test AppVeyor script for all jobs locally on my side.
I'll add commit reflecting file changes from /pull/242 first, since that has been merged already.

**Comment by namaenonaimumei** [comment]
Should be fine now.
I couldn't come up with any cleaner solution at the moment, since I was afraid of breaking CMake-side buildchain (couldn't get it to run on both Windows/Linux without heavy changes - not sure what image it is running )

**Comment by rougier** [comment]
Thanks!

**Pull request merged**
