### PR TITLE
CMAKE Install directive and limited Android Support

### PR DESCRIPTION
**Pull request by ignitusboyone**
I'm hoping you will accept these two commits. 

The first simply modifies opengl.h to include GLES3/gl3.h when __ANDROID__ is detected.

The second commit simply adds the ability to type make install for freetype-gl. The base headers and the static library will be placed in CMAKE_INSTALL_PREFIX/{include,lib}

### CODE REVIEW

**Comment by rougier** [comment]
Thanks. Does it work for any android system or is there a minimum version needed?

**Comment by ignitusboyone** [comment]
GLESv3 didn't become available in Android until Android 4.3 Jelly Bean (API 18)
Android 4.3 Jelly Bean (API 18)

I think that should be sufficient for 90-85% of current Android devices. 
https://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/

**Comment by ignitusboyone** [comment]
Header files were being installed as 004 instead of 444.   I adjusted the cmake accordingly.

**Comment by rougier** [comment]
Ok. Thanks.

**Pull request merged**
