### PR TITLE
Add ftgl namespace.

### PR DESCRIPTION
**Pull request by andystanton**
Implementation of the idea discussed by @Trouvist and @rougier in rougier/freetype-gl#40.

 * Added ftgl namespace in all freetype-gl headers, guarded by ```ifdef __cplusplus```
 * Using this namespace by default in freetype-gl.h
 * Allow override of the default with NOT_USING_FT_GL_NAMESPACE

### Usage

```cpp
#define NOT_USING_FT_GL_NAMESPACE

#include <freetype-gl.h>
#include <glm/glm.hpp>

ftgl::vec2 foo = {{100, 200}};
glm::vec2 bar = {10, 20};
```

Apologies, looks like my editor introduced some whitespace changes.

### CODE REVIEW

**Comment by rougier** [comment]
Thanks a lot. My only comment would be the actual namespace name "ftglm" that might introduce some confusion with glm (but in the meantime, it is supposed to avoid problem with glm).

**Comment by andystanton** [comment]
I'm happy to change it to something else. How about ftgl or freetypegl?

**Comment by rougier** [comment]
ftgl might be more convenient (shorter), what do you think ?

**Comment by andystanton** [comment]
ftgl sounds good to me!

I've changed ```ftglm``` to ```ftgl``` and ```NOT_USING_FT_GLM_NAMESPACE``` to ```NOT_USING_FT_GL_NAMESPACE```. This has been committed and fixed up so there's only one commit.

**Comment by rougier** [comment]
Thanks, let me test and merge.

**Comment by rougier** [comment]
Seems ok but your PR might need a rebase (because I merged your previous PR)

**Comment by andystanton** [comment]
Rebased.

**Comment by rougier** [comment]
Thanks

**Pull request merged**
