### PR TITLE
Removed GLEW for OSX (as it's not needed)

### PR DESCRIPTION
**Pull request by burito**
I've never used CMake before, so could you please double check that I got the changes correct?
There were two instances of GLEW being listed twice in there, I hope removing the duplicate was the right thing to do.

It seems to work just fine on Yosemite now, sorry I can't test on older versions. XCode 6.2.
```cmake .``` produced a happy Makefile, and ```cmake -GXcode .``` produced a happy Xcode Project file.

### CODE REVIEW

**Comment by rougier** [comment]
I'm also unable to teste on previous versions of OSX. Maybe we need some feedback first to check if things are broken or not for older OSX versions.

**Comment by burito** [comment]
It *should* work as far back as Lion, beyond that as far as I can tell is "Officially unsupported by Apple" territory, although if Apple actually supports anything appears to be a mystery to all.

**Comment by rougier** [comment]
Yes, but I would prefer to have someone to test it.

**Comment by burito** [comment]
I've been researching this a bit more. From 10.6 (snow leopard) onwards updating to Yosemite (10.10) is free. [source](http://www.apple.com/osx/how-to-upgrade/). It appears Apple is deliberately trying to stamp out older versions.

**Comment by rougier** [comment]
On Yosemite, using make (not cmake), I get:

```
Building demo-atb-agg.o...
demo-atb-agg.c:514:18: warning: implicit declaration of function 'glewInit' is invalid in C99
      [-Wimplicit-function-declaration]
    GLenum err = glewInit();
                 ^
demo-atb-agg.c:515:9: error: use of undeclared identifier 'GLEW_OK'
    if (GLEW_OK != err)
        ^
demo-atb-agg.c:518:41: warning: implicit declaration of function 'glewGetErrorString' is invalid in C99
      [-Wimplicit-function-declaration]
        fprintf( stderr, "Error: %s\n", glewGetErrorString(err) );
                                        ^
demo-atb-agg.c:518:41: warning: format specifies type 'char *' but the argument has type 'int' [-Wformat]
        fprintf( stderr, "Error: %s\n", glewGetErrorString(err) );
                                 ~~     ^~~~~~~~~~~~~~~~~~~~~~~
                                 %d
demo-atb-agg.c:521:41: warning: implicit declaration of function 'glewGetString' is invalid in C99
      [-Wimplicit-function-declaration]
    fprintf( stderr, "Using GLEW %s\n", glewGetString(GLEW_VERSION) );
                                        ^
demo-atb-agg.c:521:55: error: use of undeclared identifier 'GLEW_VERSION'
    fprintf( stderr, "Using GLEW %s\n", glewGetString(GLEW_VERSION) );
                                                      ^
4 warnings and 2 errors generated.
make: *** [demo-atb-agg.o] Error 1
```

**Comment by burito** [comment]
Nope, didn't touch the Makefile or demo-atb-agg.c, as AntTweakBar was being difficult to build on my system.

I was under the impression CMake's job was to generate Makefiles, so I naively assumed the Makefile existed for nefarious purposes beyond my reckoning.

I'll have another shot at AntTweakBar, and if successful, I'll fix the Makefile and demo-atb-agg.c

**Comment by rougier** [comment]
Thanks. There is a hand-crafted default Makefile and the CMake stuff as well. I'm used to the default Makefile system, that's the reason why (in case you wonder) :)

**Comment by burito** [comment]
Me too, CMake scares me.

    sudo port install anttweakbar

done the trick. MacPorts put it in ``/opt/local/include``, which I added to the Makefile.

The Makefile does complain about missing fonts, but it works just fine without them.

**Comment by rougier** [comment]
Yes, I had some problem with fonts because some of them cannot be distributed freely but the original AFF implementation use some in the original article at: http://www.antigrain.com/research/font_rasterization/.

Source Sans Pro and Source Code Pro might be great replacement. Can you open a PR just for the font so we can decide which ones are to be distributed along sources (might require to change examples as well)

**Comment by rougier** [comment]
Seems to be working. One problem is the cube demo which is now very slow in animation. I think the problem is related to the use of `clock()` but I cannot find who inserted this code.

**Pull request merged**
