### PR TITLE
Aligning and measuring text

### PR DESCRIPTION
**Pull request by bobkocisko**
We have a need for aligning multiple lines of text to the center or right of the text buffer (text_buffer_align).  As a side effect we can glean text measurement information (text_buffer_get_bounds).

### CODE REVIEW

**Comment by adrianbroher** [comment]
So far the pull request looks good and works as expected.  Could you please rebase the PR to fixup the commits 3788225 and 79efd3b into 79efd3b after you addressed the remarks?

**Comment by bobkocisko** [comment]
I'd be happy to rebase as soon as we work through the bool issue.

Thanks for giving this pr such quick attention!

**Comment by bobkocisko** [comment]
Ok I think this is ready to go.  Is there anything else you need from me before it can be merged?

**Comment by rougier** [comment]
Good for me.

**Comment by adrianbroher** [comment]
Merged PR and added you to the contributor list.  Thank you.

**Comment by bobkocisko** [comment]
Thank you!

**Pull request merged**
